### ISSUE TITLE
gpg --card-status

### ISSUE THREAD

**Issue by umbertix** [demonbane/wsl-gpg-systemd#1]
First of all thx for the repo, I have tried to use it with the usecase of using a gpg card. Unfortunetly the output of the `gpg --card-status` command is still "empty". I have done the changes on the path to point to the `S.gpg-agent` but still to no avail.

Any ideas on what could be the problem or how I could debug a bit more on my own would be greatly appreciated, I'm quite out of my depth.

Thx

**Comment by demonbane** [comment]
If you edited `gpg-agent@.service` that should have done the trick. Did you remember to do a `systemctl --user daemon-reload` after making the changes? I just tested it locally and it works just fine.

If that doesn't work and if you want to troubleshoot further:

1. Open a powershell/cmd window and try running `gpg --card-status` there and make sure you get valid output
2. If that works, check the output of `gpgconf --list-dirs agent-socket` (in Windows, not WSL) and compare it with what you have in `~/.config/systemd/user/gpg-agent@.service`. With the exception of the `\` being changed to `/`, the paths should be identical.
3. If none of that helps, try restarting Windows (to make sure WSL is fully reloaded), then before opening a WSL terminal, go to a powershell/cmd window and run `gpg --card-status` first. This will make sure that the card is working, and wake the Windows GPG agent. Then fire up a WSL shell and try `gpg --card-status` again and it should work.
